"""Additional seed questions: deepens every subject bank to 16 questions."""

AR = [
    "Both A and R are true, and R is the correct explanation of A",
    "Both A and R are true, but R is NOT the correct explanation of A",
    "A is true, but R is false",
    "A is false, but R is true",
]

QUESTIONS = [
    # ---------------- DATA STRUCTURES (+6) ----------------
    {
        "subject": "DS", "topic": "Stacks & Queues", "difficulty": "very_hard", "experience_min": 5,
        "type": "single",
        "text": "For the infix expression a - b ^ c ^ d where ^ is right-associative and has higher precedence than -, which postfix expression does the standard shunting-yard algorithm produce?",
        "options": ["a b c d ^ ^ -", "a b c ^ d ^ -", "a b c d ^ ^ - and a b c ^ d ^ - are both valid", "a b - c d ^ ^"],
        "answer": [0],
        "explanation": "With right associativity, ^ is pushed and the second ^ (same precedence, right-assoc) does NOT pop the first, so the stack holds ^ ^ and the output becomes a b c d ^ ^ -, which groups as a - (b ^ (c ^ d)).",
    },
    {
        "subject": "DS", "topic": "Stacks & Queues", "difficulty": "hard", "experience_min": 3,
        "type": "scenario",
        "text": "A circular queue of capacity 8 is implemented with head/tail indices. After enqueues fill it, you dequeue 3 items, then enqueue 2. What is the safest way to compute the number of elements?",
        "options": [
            "(tail - head + capacity) % capacity — handles wrap-around correctly",
            "tail - head, always",
            "head - tail",
            "capacity - head",
        ],
        "answer": [0],
        "explanation": "Modular arithmetic (tail - head + N) % N is the canonical wrap-safe length formula for a circular buffer; a bare tail-head is wrong when the queue has wrapped.",
    },
    {
        "subject": "DS", "topic": "Binary Search Trees", "difficulty": "very_hard", "experience_min": 6,
        "type": "numerical",
        "text": "Start with an empty AVL tree and insert 10, 20, 30, 40, 50, 25 in order. What is the preorder traversal of the final AVL tree?",
        "options": ["30 20 10 40 25 50", "20 10 30 25 40 50", "30 20 10 25 40 50", "10 20 30 40 50 25"],
        "answer": [2],
        "explanation": "After 10,20,30 the RR rotation gives 20(10,30). 40 and 50 attach without rotation. Inserting 25 under 30 makes 20 unbalanced (its right subtree is left-heavy) → RL double rotation: rotate right at 40, then left at 20 → root 30 with left 20 (children 10, 25) and right 40 (child 50). Preorder: 30 20 10 25 40 50.",
    },
    {
        "subject": "DS", "topic": "Sorting", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Which statement about counting sort and radix sort is correct?",
        "options": [
            "Counting sort is O(n + k) and stable, making it the required stable subroutine inside LSD radix sort; both are non-comparison sorts",
            "Counting sort is a comparison sort with O(n log n) average",
            "Radix sort cannot sort strings",
            "Radix sort is always faster than quicksort for large n",
        ],
        "answer": [0],
        "explanation": "Counting sort runs in O(n+k) time and O(k) space and is stable — stability is exactly why radix sort uses it per digit. Radix sort can sort strings (byte-wise) and is not universally faster than quicksort (constant factors and cache behavior matter).",
    },
    {
        "subject": "DS", "topic": "Balanced Structures", "difficulty": "expert", "experience_min": 10,
        "type": "scenario",
        "text": "For an in-memory ordered map with ~10^6 keys, frequent range scans, and occasional deletes, which structure is the best default, and why?",
        "options": [
            "A B-tree (or B+ tree) with a large fanout — cache-efficient range scans and O(log_B n) operations",
            "A linked list with binary search on elements",
            "A hash map with ordered iteration via sorting on demand",
            "A trie of fixed bit width — always optimal",
        ],
        "answer": [0],
        "explanation": "Hash maps lose ordering; sorted-on-demand is O(n log n) per scan; B-trees give cache-friendly sequential access for range scans and logarithmic updates, which is why databases and Rust's BTreeMap use them.",
    },
    {
        "subject": "DS", "topic": "Graphs", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "You run DFS on a directed graph and want to detect cycles. Which statement is correct?",
        "options": [
            "A back edge (an edge to a vertex still on the recursion stack) indicates a cycle; detecting it requires tracking the current DFS path, not just visited status",
            "Any visited vertex reached twice implies a cycle",
            "DFS cannot detect cycles in directed graphs",
            "A forward edge implies a cycle",
        ],
        "answer": [0],
        "explanation": "In directed graphs, seeing an already-visited node is not enough (cross edges exist); only an edge to a node on the current recursion stack is a back edge proving a cycle. Undirected cycle detection uses visited-status plus the parent check.",
    },

    # ---------------- DBMS (+4) ----------------
    {
        "subject": "DBMS", "topic": "Query Optimization", "difficulty": "very_hard", "experience_min": 8,
        "type": "numerical",
        "text": "Join R(A,B) and S(B,C) on B. R has 10,000 pages, S has 100 pages, and 201 buffer pages are available. Sort-merge join sorts R (10,000 pages) and S (100 pages). Approximately what is the total I/O cost including sorting?",
        "options": [
            "About 50,000 I/Os — sorting R costs ~40,000 I/Os (two passes), S ~200, and the final merge streams both once (~10,100)",
            "About 100,000 I/Os — every page of R is read per probe",
            "About 40,000 I/Os — sorting alone, ignoring the merge",
            "About 1,000 I/Os",
        ],
        "answer": [0],
        "explanation": "R: first pass reads+writes 10,000 pages → 20,000 I/Os creating ~50 runs; second pass (single merge, 50 < 200 runs) reads+writes again → 20,000. S: ~200 I/Os. Final merge streams both sorted relations once: 10,100. Total ≈ 50,300 — orders of magnitude below block nested-loop join for this size.",
    },
    {
        "subject": "DBMS", "topic": "Transactions & Concurrency", "difficulty": "expert", "experience_min": 10,
        "type": "single",
        "text": "Which statement about view serializability is correct?",
        "options": [
            "A schedule is view-serializable if it is conflict-serializable OR contains blind writes that preserve a serial order — the polynomial check is harder than conflict analysis",
            "View serializability equals conflict serializability for all schedules",
            "View-serializable schedules are always conflict-serializable",
            "Any schedule produced by 2PL is view-serializable by construction",
        ],
        "answer": [0],
        "explanation": "View equivalence requires each read to see the same writer as in the serial schedule; blind writes can make non-conflict-serializable schedules view-serializable, and testing view serializability is NP-complete in general — which is why engines enforce conflict-serializable protocols like strict 2PL.",
    },
    {
        "subject": "DBMS", "topic": "Transactions & Concurrency", "difficulty": "hard", "experience_min": 5,
        "type": "scenario",
        "text": "Three transactions wait: T1 holds A, wants B; T2 holds B, wants C; T3 holds C, wants A. A timeout-based detector aborts T2. What happens next?",
        "options": [
            "T2's locks are released, T1 and T3 can proceed, and T2 is restarted — the cycle is broken",
            "T1 aborts too because timeouts cascade",
            "The deadlock returns because T2's requests are forgotten",
            "The database shuts down to avoid livelock",
        ],
        "answer": [0],
        "explanation": "Aborting the victim releases its locks (B), allowing T1 to acquire B and T3 to acquire A after T1 finishes; the waits-for cycle disappears and the victim restarts. Timeout detection needs no wait-for graph but can abort innocent transactions.",
    },
    {
        "subject": "DBMS", "topic": "Indexing", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "What is the main difference between a B-tree and a B+ tree?",
        "options": [
            "In a B+ tree all data lives in the leaves, which are linked for sequential scans; internal nodes hold only keys — maximizing fanout and enabling range scans",
            "A B+ tree stores data in every node like a B-tree",
            "B-trees are always taller than B+ trees",
            "B+ trees cannot support equality lookups",
        ],
        "answer": [0],
        "explanation": "The defining property: B+ leaves contain all keys + data and are chained; internal nodes are pure indexes. This raises fanout (fewer levels) and makes range scans sequential — why virtually all relational engines use B+ trees.",
    },

    # ---------------- OS (+4) ----------------
    {
        "subject": "OS", "topic": "Memory Management", "difficulty": "very_hard", "experience_min": 7,
        "type": "numerical",
        "text": "A process has reference string 1,2,3,4,1,2,5,1,2,3,4,5 with 3 frames. How many page faults occur under LRU, and what is the notable difference from FIFO here?",
        "options": [
            "LRU: 10 faults; FIFO: 9 faults — the classic string where FIFO beats LRU",
            "LRU: 9 faults; FIFO: 9 faults",
            "LRU: 12 faults; FIFO: 12 faults",
            "LRU: 10 faults; FIFO: 10 faults — identical counts",
        ],
        "answer": [0],
        "explanation": "LRU walk: 1,2,3 fault (3); 4 evicts 1 (4); 1 evicts 2 (5); 2 evicts 3 (6); 5 evicts 4 (7); 1 hit; 2 hit; 3 evicts 5 (8); 4 evicts 1 (9); 5 evicts 2 (10) → 10. FIFO: 1,2,3 (3); 4 evicts 1 (4); 1 evicts 2 (5); 2 evicts 3 (6); 5 evicts 4 (7); 1,2 hit; 3 evicts 1 (8); 4 evicts 2 (9); 5 hit → 9. This is the textbook example where FIFO's older-eviction policy happens to serve the later refs better.",
    },
    {
        "subject": "OS", "topic": "Synchronization", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "What distinguishes a counting semaphore from a mutex?",
        "options": [
            "A semaphore is a general counter that need not be released by the same thread that acquired it; a mutex is a binary ownership lock that must be released by its owner",
            "Semaphores are always binary and mutexes can count",
            "Mutexes cannot protect shared data",
            "Semaphores cannot be used for signaling",
        ],
        "answer": [0],
        "explanation": "Semaphores generalize to N permits and their release can come from another thread (used for signaling/producer-consumer); a mutex has strict ownership semantics, making it safer for mutual exclusion.",
    },
    {
        "subject": "OS", "topic": "Memory Management", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "What is the purpose of an ASID (Address Space Identifier) in a TLB?",
        "options": [
            "It tags TLB entries with their address space so entries from different processes do not collide, eliminating the need to flush the TLB on every context switch",
            "It stores the physical frame number for faster lookup",
            "It prevents TLB entry allocation failures",
            "It accelerates disk I/O for swapped pages",
        ],
        "answer": [0],
        "explanation": "Without ASIDs, each context switch flushes the TLB (or every entry must be validated); ASIDs let entries from several processes coexist and only entries of the same ASID match during a translation.",
    },
    {
        "subject": "OS", "topic": "Processes & IPC", "difficulty": "expert", "experience_min": 10,
        "type": "debugging",
        "text": "A server repeatedly spawns child processes for tasks. Over a weekend the machine becomes unresponsive; ps shows hundreds of 'defunct' (zombie) children. Which statement is correct?",
        "options": [
            "The parent never called wait()/waitpid(), so children's exit statuses accumulate as zombies; killing the parent lets init reap them, and the fix is a SIGCHLD handler or wait loop",
            "Zombies consume memory proportional to the children's heap, so the machine runs out of RAM",
            "Defunct processes are still running and must be killed individually",
            "This is normal and harmless",
        ],
        "answer": [0],
        "explanation": "A zombie holds only a small PCB entry until the parent reaps it via wait(). Hundreds are a symptom of a missing wait/SIGCHLD handler. Killing the parent orphans them to init which reaps them. Zombies do not hold the child's former memory.",
    },

    # ---------------- CN (+6) ----------------
    {
        "subject": "CN", "topic": "Transport Layer", "difficulty": "hard", "experience_min": 4,
        "type": "numerical",
        "text": "During TCP connection establishment, the client's initial sequence number (ISN) is 1000 and the server's is 5000. What are the sequence/ack numbers in the three-way handshake?",
        "options": [
            "SYN(seq=1000) → SYN+ACK(seq=5000, ack=1001) → ACK(seq=1001, ack=5001)",
            "SYN(seq=1000) → SYN+ACK(seq=5000, ack=1000) → ACK(seq=5000, ack=1000)",
            "SYN(seq=1000) → SYN+ACK(seq=1001, ack=5000) → ACK(seq=1001, ack=5000)",
            "SYN(seq=1000) → SYN+ACK(seq=5000, ack=1001) → ACK(seq=1000, ack=5000)",
        ],
        "answer": [0],
        "explanation": "SYN consumes one sequence number, so the receiver ACKs ISN+1: server ACKs 1001, client ACKs 5001, and the client's data seq continues at 1001. The ACK numbers reflect the consumed SYN.",
    },
    {
        "subject": "CN", "topic": "Network Layer", "difficulty": "hard", "experience_min": 3,
        "type": "numerical",
        "text": "Aggregate the networks 192.168.1.0/24, 192.168.2.0/24, 192.168.3.0/24, and 192.168.4.0/24 into the smallest single CIDR block.",
        "options": [
            "192.168.0.0/21 — covers 192.168.0.0–192.168.7.255",
            "192.168.0.0/22 — covers 192.168.0.0–192.168.3.255",
            "192.168.0.0/20",
            "Cannot be aggregated because the blocks are not contiguous",
        ],
        "answer": [1],
        "explanation": "The four /24s span 192.168.0.0 to 192.168.3.255 (a 1024-address block = /22). Note 192.168.0.0/22 includes .0/.1/.2/.3 but NOT .4 — a /21 would include extra space (.0–.7), so /22 is the smallest exact cover.",
    },
    {
        "subject": "CN", "topic": "Security", "difficulty": "very_hard", "experience_min": 8,
        "type": "single",
        "text": "In a TLS 1.2 full handshake, in which order does the client verify the server?",
        "options": [
            "Client sends ClientHello with supported ciphers → server replies ServerHello + Certificate + ServerKeyExchange + ServerHelloDone → client validates the certificate chain, then sends its key share / finished",
            "Client validates the certificate before sending ClientHello",
            "The server authenticates the client before any certificate exchange",
            "Certificate validation happens only after the tunnel is established",
        ],
        "answer": [0],
        "explanation": "The server presents its certificate after ServerHello; the client validates chain, hostname, and expiry, then completes the key exchange. ClientHello has no certificate — validation cannot precede it.",
    },
    {
        "subject": "CN", "topic": "Network Layer", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Which statement about ICMP is correct?",
        "options": [
            "ICMP is carried inside IP and used for diagnostics and error reporting (e.g. destination unreachable, echo request/reply); it is not used for normal application data transport",
            "ICMP replaces ARP for address resolution",
            "ICMP is a transport-layer protocol like TCP",
            "Routers always drop ICMP by design",
        ],
        "answer": [0],
        "explanation": "ICMP is encapsulated in IP packets and reports network errors/control info (ping/traceroute use it). It is neither a transport protocol for applications nor an address-resolution mechanism.",
    },
    {
        "subject": "CN", "topic": "Link Layer", "difficulty": "hard", "experience_min": 4,
        "type": "assertion_reason",
        "text": "Assertion (A): Two hosts on the same Ethernet segment communicate using MAC addresses, not IP addresses, at the data link layer.\nReason (R): The IP address of the destination host is resolved to its MAC address by ARP before the frame is sent.",
        "options": AR,
        "answer": [0],
        "explanation": "IP provides the logical address; the Ethernet frame header carries the destination MAC obtained via ARP. Both statements are true and R explains the mechanism behind A.",
    },
    {
        "subject": "CN", "topic": "Application Layer", "difficulty": "very_hard", "experience_min": 7,
        "type": "single",
        "text": "Which statement about HTTP/2 multiplexing is correct?",
        "options": [
            "Multiple streams share one TCP connection, and head-of-line blocking at the HTTP layer is eliminated — but TCP-level loss can still block all streams on that connection",
            "HTTP/2 opens a separate TCP connection per resource",
            "HTTP/2 only multiplexes responses, never requests",
            "HTTP/2 removes the need for TLS",
        ],
        "answer": [0],
        "explanation": "Stream multiplexing removes HTTP-level HOL blocking, but the single TCP connection still experiences transport-level HOL blocking when a segment is lost. HTTP/2 does not require TLS (though browsers enforce h2 over TLS).",
    },

    # ---------------- CO (+8) ----------------
    {
        "subject": "CO", "topic": "Pipelining", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "Which hazard class is handled by forwarding (bypassing), and which is NOT?",
        "options": [
            "Forwarding resolves data hazards (RAW) where the needed value is available from an earlier pipeline stage; load-use hazards may still require one stall, and control hazards need branch prediction/delayed slots",
            "Forwarding resolves control hazards completely",
            "Forwarding eliminates structural hazards",
            "Forwarding cannot resolve any data hazard",
        ],
        "answer": [0],
        "explanation": "Bypass networks feed EX results back to earlier stages, covering most RAW hazards; a load's data arrives only after MEM, so load-use still stalls one cycle. Control (branch) hazards are handled by prediction, not forwarding.",
    },
    {
        "subject": "CO", "topic": "Data Representation", "difficulty": "hard", "experience_min": 3,
        "type": "code",
        "text": "On a little-endian machine, int x = 0x01020304 is stored at address 0x1000. What bytes are at 0x1000, 0x1001, 0x1002, 0x1003?",
        "options": ["04 03 02 01", "01 02 03 04", "04 02 03 01", "01 04 02 03"],
        "answer": [0],
        "explanation": "Little-endian stores the least significant byte first: 0x04 at the lowest address, then 0x03, 0x02, 0x01. Big-endian would store 01 02 03 04.",
    },
    {
        "subject": "CO", "topic": "Arithmetic", "difficulty": "very_hard", "experience_min": 6,
        "type": "numerical",
        "text": "In IEEE-754 single precision, which rounding mode makes 1.0 + 2^-24 round to 1.0 (nearest-even), and what is 1.0 + 2^-23?",
        "options": [
            "Round-to-nearest-even: 2^-24 is half an ulp below the halfway point so it rounds to 1.0; 2^-23 is exactly one ulp so 1.0 + 2^-23 = next representable (1 + 2^-23)",
            "Round-half-up: both round up",
            "1.0 + 2^-24 rounds to 2.0",
            "Neither value is representable",
        ],
        "answer": [0],
        "explanation": "At exponent 0 the ulp is 2^-23; the halfway point between 1.0 and 1+ulp is 1.0 + 2^-24. Nearest-even rounds exact halfway (2^-24) to the even mantissa (1.0), while 2^-23 lands exactly on the next value.",
    },
    {
        "subject": "CO", "topic": "Instruction Sets", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "In a fixed-length MIPS-style instruction, why are jump instructions able to target a full 256 MB-aligned region while branches are limited to ±128 KB?",
        "options": [
            "The J-type format carries a 26-bit target that is shifted left by 2 and ORed with the upper bits of the PC; I-type branches carry a 16-bit immediate",
            "Branches use 32-bit addresses stored in memory",
            "Jump instructions execute in fewer cycles",
            "The assembler rewrites far branches into function calls",
        ],
        "answer": [0],
        "explanation": "J-type: 6-bit opcode + 26-bit address, shifted to 28 bits, combined with the PC's top 4 bits → ±256 MB region. I-type branch offset is 16 bits (shifted → ±128 KB), which is why far branches need jump-and-link trampolines.",
    },
    {
        "subject": "CO", "topic": "Storage", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Which statement about RAID levels is correct?",
        "options": [
            "RAID 5 stripes data with distributed parity and tolerates ONE disk failure; RAID 6 adds a second parity block and tolerates TWO",
            "RAID 1 stripes data for speed and has no redundancy",
            "RAID 0 provides redundancy by mirroring",
            "RAID 6 tolerates any number of failures",
        ],
        "answer": [0],
        "explanation": "RAID 5: single distributed parity, one-fault tolerant. RAID 6: two independent parity blocks, two-fault tolerant. RAID 0 is pure striping (no redundancy); RAID 1 is mirroring.",
    },
    {
        "subject": "CO", "topic": "System Interconnect", "difficulty": "expert", "experience_min": 10,
        "type": "single",
        "text": "Why have modern processors moved from shared buses to point-to-point interconnects (e.g. Intel QPI/UPI, AMD Infinity Fabric)?",
        "options": [
            "Shared buses cannot scale bandwidth with core count and become electrical/bandwidth bottlenecks; point-to-point links scale bandwidth and reduce contention",
            "Shared buses are faster than point-to-point",
            "Point-to-point links require more pins but are electrically identical",
            "Buses cannot carry coherence traffic",
        ],
        "answer": [0],
        "explanation": "A shared bus has one collision domain and a fixed bandwidth shared by all agents; point-to-point links give each pair dedicated bandwidth, scale with topology, and handle NUMA coherence traffic better.",
    },
    {
        "subject": "CO", "topic": "I/O Systems", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "In a typical interrupt-driven I/O sequence, which step comes directly after the device raises an interrupt request?",
        "options": [
            "The CPU finishes the current instruction, pushes context, and jumps to the interrupt vector; the handler identifies the device and services it",
            "The CPU polls the device every cycle",
            "The device writes directly to the application buffer",
            "The OS schedules a new process immediately",
        ],
        "answer": [0],
        "explanation": "Interrupt delivery completes the current instruction, saves minimal state, and vectors to the handler (possibly through an APIC/vector table); the handler then acknowledges/serves the device. DMA devices transfer data with only completion interrupts.",
    },
    {
        "subject": "CO", "topic": "Cache Design", "difficulty": "very_hard", "experience_min": 8,
        "type": "single",
        "text": "In the MESI protocol, which transition requires a bus transaction to memory, and which state handles a read by another core without a memory access?",
        "options": [
            "M→I on an external read request triggers a writeback to memory; S and E states serve reads from other caches with a bus snoop but no memory traffic",
            "S→M requires a writeback",
            "I→E requires a memory write",
            "MESI cannot serve reads from other caches",
        ],
        "answer": [0],
        "explanation": "When a core in M sees a snooped read, it must write the dirty line back to memory before downgrading (to S or I). Shared (S) and exclusive (E) lines can be supplied to another cache via snoop without touching main memory.",
    },

    # ---------------- JAVA (+6) ----------------
    {
        "subject": "JAVA", "topic": "Strings", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "In a loop concatenating 10,000 strings, why is StringBuilder preferred over s += piece?",
        "options": [
            "s += piece creates a new String object each iteration — O(n²) copying; StringBuilder mutates one buffer in amortized O(n)",
            "Strings are mutable, so += is already efficient",
            "StringBuilder cannot be used in loops",
            "The compiler automatically optimizes all concatenations to StringBuilder regardless of scope",
        ],
        "answer": [0],
        "explanation": "String is immutable; += allocates a fresh char[] and copies every time → quadratic. The javac 'StringBuilder' optimization only applies to concatenations in a single expression/statement, not loops with evolving variables.",
    },
    {
        "subject": "JAVA", "topic": "Object Semantics", "difficulty": "very_hard", "experience_min": 6,
        "type": "single",
        "text": "A class overrides equals() using mutable fields but does NOT override hashCode(). Which statement describes the resulting bug?",
        "options": [
            "The class violates the equals/hashCode contract: equal objects may produce different hashCodes, breaking HashSet/HashMap lookups and causing duplicates",
            "It is always fine to override only equals()",
            "The JVM recomputes hashCode from the identity",
            "HashMap will throw an exception at construction",
        ],
        "answer": [0],
        "explanation": "The contract requires equal objects to have equal hash codes. With equals on mutable fields and identity hashCode, two 'equal' objects can land in different buckets — lookup fails and duplicates appear. Mutating key fields in a HashSet is another classic trap.",
    },
    {
        "subject": "JAVA", "topic": "Language Semantics", "difficulty": "hard", "experience_min": 4,
        "type": "code",
        "text": "class A { static { System.out.print(\"A\"); } }\nclass B extends A { static { System.out.print(\"B\"); } }\npublic class Main { public static void main(String[] a) { new B(); } }\nWhat prints?",
        "options": ["AB", "BA", "A", "B"],
        "answer": [0],
        "explanation": "Class initialization runs superclass static initializers first, so A's static block prints before B's. Instantiation then runs instance initializers/constructors in the same superclass-first order.",
    },
    {
        "subject": "JAVA", "topic": "Exceptions", "difficulty": "very_hard", "experience_min": 5,
        "type": "code",
        "text": "static int f() { try { return 1; } finally { return 2; } }\nWhat does f() return?",
        "options": [
            "2 — a return in finally overrides the try's return value",
            "1 — the try return wins",
            "Compile error",
            "Either 1 or 2 depending on the JVM",
        ],
        "answer": [0],
        "explanation": "If finally completes abruptly with a return, that value replaces the pending return from try. This is a notorious anti-pattern: never return from finally.",
    },
    {
        "subject": "JAVA", "topic": "Streams & Lambdas", "difficulty": "expert", "experience_min": 9,
        "type": "scenario",
        "text": "A parallel stream over a 10^7-element list is SLOWER than the sequential version. Which is the most likely cause?",
        "options": [
            "The workload is cheap per element and the input is small relative to fork-join overhead, or the operation has a shared mutable accumulator causing contention",
            "Parallel streams are always slower because of the GIL",
            "The list should be converted to an array first",
            "The collector is not a Collector type",
        ],
        "answer": [0],
        "explanation": "Parallelism pays only when per-element work outweighs split/join/merge overhead and the reduction is associative without contention. A shared mutable accumulator (non-thread-safe or contested) serializes the work and adds overhead.",
    },
    {
        "subject": "JAVA", "topic": "JVM Internals", "difficulty": "very_hard", "experience_min": 8,
        "type": "single",
        "text": "What is the difference between ClassNotFoundException and NoClassDefFoundError?",
        "options": [
            "ClassNotFoundException is a checked exception thrown when a class is not found by the class loader (e.g. missing jar); NoClassDefFoundError is an Error thrown when a class was present at compile time but the runtime class loader cannot load it (e.g. missing dependency at runtime)",
            "They are the same type",
            "NoClassDefFoundError is checked",
            "ClassNotFoundException indicates the JVM crashed",
        ],
        "answer": [0],
        "explanation": "The names look similar but the semantics differ: CNFE is thrown from Class.forName/loadClass; NCDFE occurs during linking of a previously seen class (its static init failed or a dependency vanished). Handling them correctly requires distinguishing loader-time vs link-time failures.",
    },

    # ---------------- SE (+8) ----------------
    {
        "subject": "SE", "topic": "Estimation & Process", "difficulty": "hard", "experience_min": 5,
        "type": "numerical",
        "text": "Using a simple COCOMO-style effort model E = a(KLOC)^b with a=2.4, b=1.05, a 50 KLOC project estimates how many person-months?",
        "options": ["Approximately 146 person-months", "Approximately 120 person-months", "Approximately 240 person-months", "Exactly 50 person-months"],
        "answer": [0],
        "explanation": "E = 2.4 × 50^1.05. 50^1.05 = e^(1.05 × ln 50) = e^(1.05 × 3.912) = e^4.108 ≈ 60.8; × 2.4 ≈ 146 person-months (the published basic-COCOMO figure for 50 KLOC). Models like this illustrate super-linear effort growth with size.",
    },
    {
        "subject": "SE", "topic": "Design", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Which coupling type is the strongest (worst) between modules?",
        "options": [
            "Content coupling — one module directly modifies or relies on the internals of another",
            "Data coupling — passing only primitive values",
            "Control coupling — passing a flag to choose behavior",
            "Stamp coupling — passing a whole structure but using part of it",
        ],
        "answer": [0],
        "explanation": "Coupling strength (worst → best): content > common > control > stamp > data. Content coupling breaks encapsulation entirely; data coupling is the weakest (best).",
    },
    {
        "subject": "SE", "topic": "Quality & Testing", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "The 'test pyramid' recommends which distribution of automated tests?",
        "options": [
            "Many fast unit tests at the base, fewer integration tests, and fewest end-to-end tests",
            "Mostly end-to-end tests with few unit tests",
            "Equal numbers of every kind",
            "Only manual testing in production",
        ],
        "answer": [0],
        "explanation": "Unit tests are fast, cheap, and pinpoint failures; end-to-end tests are slow and brittle — hence the pyramid shape. Inverted pyramids lead to slow, flaky suites and long feedback loops.",
    },
    {
        "subject": "SE", "topic": "DevOps & Reliability", "difficulty": "very_hard", "experience_min": 7,
        "type": "single",
        "text": "What is the difference between continuous delivery and continuous deployment?",
        "options": [
            "Continuous delivery keeps every change releasable to production at any time (deployment is a manual decision); continuous deployment automatically ships every change that passes the pipeline",
            "They are synonyms",
            "Continuous deployment requires nightly builds only",
            "Continuous delivery forbids automated testing",
        ],
        "answer": [0],
        "explanation": "CDelivery = pipeline that produces a deployable artifact on every commit, with a human approval gate; CDeployment = the gate is removed. Many organizations do delivery without deployment to control release timing.",
    },
    {
        "subject": "SE", "topic": "Architecture", "difficulty": "hard", "experience_min": 4,
        "type": "assertion_reason",
        "text": "Assertion (A): The structure of an organization tends to mirror the structure of the systems it builds (Conway's law).\nReason (R): Teams communicate through their interfaces, and systems are constrained to match the communication paths of the people who build them.",
        "options": AR,
        "answer": [0],
        "explanation": "Conway's law is an observation about communication structures: the interfaces between components follow the boundaries between teams. Both statements are true and R explains A — the reason 'inverse Conway maneuver' reorganizes teams to get the architecture you want.",
    },
    {
        "subject": "SE", "topic": "Quality & Testing", "difficulty": "expert", "experience_min": 10,
        "type": "scenario",
        "text": "After a major outage, the team debates the postmortem. Which practice is most effective for preventing recurrence?",
        "options": [
            "A blameless postmortem that identifies contributing factors and concrete, owned action items with deadlines, reviewed in a follow-up",
            "Finding and punishing the engineer who caused it",
            "Rewriting the entire system immediately",
            "Closing the incident without documentation",
        ],
        "answer": [0],
        "explanation": "Blameless analysis surfaces systemic factors (tooling, process, monitoring gaps) instead of driving mistakes underground; owned action items with follow-up reviews are what actually change outcomes. Punishment suppresses reporting and does not fix root causes.",
    },
    {
        "subject": "SE", "topic": "Requirements & Contracts", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Which example is a NON-functional requirement?",
        "options": [
            "The system must respond to 95% of read requests within 200 ms",
            "Users must be able to upload a profile picture",
            "The system must calculate GST on invoices",
            "Admins must be able to deactivate an account",
        ],
        "answer": [0],
        "explanation": "Non-functional requirements constrain quality attributes (performance, security, usability, availability). The others describe specific functions the system performs.",
    },
    {
        "subject": "SE", "topic": "DevOps & Reliability", "difficulty": "hard", "experience_min": 5,
        "type": "single",
        "text": "Under semantic versioning, which version bump is correct for an API change that is backward-INCOMPATIBLE?",
        "options": [
            "Major version bump (2.3.1 → 3.0.0)",
            "Minor version bump (2.3.1 → 2.4.0)",
            "Patch version bump (2.3.1 → 2.3.2)",
            "No bump; API changes do not affect versioning",
        ],
        "answer": [0],
        "explanation": "SemVer: MAJOR for incompatible changes, MINOR for backward-compatible additions, PATCH for backward-compatible fixes. Breaking consumers without a major bump violates the contract and breaks downstream builds.",
    },

    # ---------------- ALGO (+6) ----------------
    {
        "subject": "ALGO", "topic": "Randomized Algorithms", "difficulty": "hard", "experience_min": 5,
        "type": "numerical",
        "text": "What is the expected time of randomized quickselect (Hoare's selection) for finding the k-th smallest of n elements, and its worst case?",
        "options": ["Expected O(n), worst case O(n²)", "Expected O(n log n), worst case O(n²)", "Expected O(n), worst case O(n log n)", "Expected O(log n), worst case O(n)"],
        "answer": [0],
        "explanation": "With random pivots, the expected work satisfies T(n) ≤ T(3n/4) + O(n) → O(n). An adversarial pivot sequence (always extreme) gives O(n²). Deterministic median-of-medians achieves O(n) worst case with a large constant.",
    },
    {
        "subject": "ALGO", "topic": "Graph Algorithms", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "Dijkstra's algorithm is run on a graph containing a negative-weight edge but no negative cycles. What happens?",
        "options": [
            "It may still compute WRONG shortest paths — the greedy settled-set argument assumes non-negative weights, so a negative edge can invalidate an already-finalized distance",
            "It is always correct without negative cycles",
            "It throws an exception",
            "It degrades to O(n³) but stays correct",
        ],
        "answer": [0],
        "explanation": "Dijkstra finalizes a vertex's distance when extracted; a negative edge can later produce a shorter path through an already-settled vertex. Correct algorithms for negative edges are Bellman–Ford or SPFA-style approaches.",
    },
    {
        "subject": "ALGO", "topic": "Dynamic Programming", "difficulty": "very_hard", "experience_min": 6,
        "type": "numerical",
        "text": "For LCS of 'ABCBDAB' and 'BDCABA', what is the LCS length, and what is the DP complexity?",
        "options": [
            "Length 4 ('BCBA' or 'BDAB'); O(n·m) time and O(n·m) space (O(min(n,m)) with the space-optimized variant)",
            "Length 3; O(n·m)",
            "Length 5; O(n²)",
            "Length 4; O(n log m)",
        ],
        "answer": [0],
        "explanation": "The classic result: LCS length is 4 (e.g. BCBA or BDAB). The standard DP is O(nm); the reconstruction needs the full table, but length-only can use two rows.",
    },
    {
        "subject": "ALGO", "topic": "Complexity Theory", "difficulty": "expert", "experience_min": 10,
        "type": "single",
        "text": "Which statement about hash functions and adversarial inputs is correct for a chained hash table using a fixed hash function h?",
        "options": [
            "An adversary who knows h can always construct n keys that collide, forcing O(n) per operation — universal hashing picks h randomly from a family to bound the expected worst case",
            "Fixed hash functions are always secure",
            "Collisions are impossible with chaining",
            "Universal hashing guarantees O(1) worst case for every input",
        ],
        "answer": [0],
        "explanation": "A fixed h is deterministic: input can be precomputed to map everything to one bucket (this is how hash-collision DoS attacks work). Universal families randomize h per table so the expected number of collisions is O(1) regardless of the input — though not worst-case O(1).",
    },
    {
        "subject": "ALGO", "topic": "Graph Algorithms", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Which DFS-based criterion correctly detects a cycle in a DIRECTED graph?",
        "options": [
            "A back edge — an edge pointing to a vertex still on the current recursion stack",
            "Any edge to a visited vertex",
            "A tree edge",
            "A cross edge",
        ],
        "answer": [0],
        "explanation": "Only back edges (to gray/on-stack vertices) imply a directed cycle; cross and forward edges to already-finished black vertices are harmless. This requires coloring, not just visited flags.",
    },
    {
        "subject": "ALGO", "topic": "Divide & Conquer", "difficulty": "very_hard", "experience_min": 8,
        "type": "single",
        "text": "What is the guarantee of the median-of-medians (BFPRT) selection algorithm?",
        "options": [
            "Deterministic O(n) worst-case selection by partitioning around a pivot that is provably between the 30th and 70th percentiles",
            "Expected O(n) with an adversarial worst case of O(n²)",
            "O(n log n) worst case",
            "O(1) after preprocessing",
        ],
        "answer": [0],
        "explanation": "Grouping into 5s and taking the median of group medians yields a pivot with at least 3n/10 elements on each side, giving the recurrence T(n) ≤ T(n/5) + T(7n/10) + O(n) → O(n) deterministically. The constant is large, so it is mostly of theoretical interest.",
    },

    # ---------------- ML (+6) ----------------
    {
        "subject": "ML", "topic": "Model Selection", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Adding more irrelevant features to a dataset typically:",
        "options": [
            "Increases training variance and the risk of overfitting for flexible models; feature selection/regularization or more data mitigates it",
            "Always improves test accuracy",
            "Has no effect on any model",
            "Reduces the need for cross-validation",
        ],
        "answer": [0],
        "explanation": "Irrelevant features give models more ways to fit noise — variance grows and generalization suffers. Regularization (L1/L2), feature selection, and more data are the standard remedies.",
    },
    {
        "subject": "ML", "topic": "Linear Models", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Which statement about logistic regression is correct?",
        "options": [
            "It models the log-odds as a linear function of the features; the decision boundary is linear in feature space",
            "It always produces a nonlinear decision boundary",
            "It requires the data to be linearly separable",
            "It is a generative model",
        ],
        "answer": [0],
        "explanation": "logit(p) = w·x + b ⇒ the boundary where p = 0.5 is the hyperplane w·x + b = 0. It is a discriminative model, does not require separability, and (with feature transforms) can express nonlinear boundaries.",
    },
    {
        "subject": "ML", "topic": "Model Selection", "difficulty": "very_hard", "experience_min": 6,
        "type": "single",
        "text": "In k-fold cross-validation, which choice of k has the LOWEST bias but the HIGHEST variance in the performance estimate?",
        "options": [
            "Leave-one-out (k = n) — nearly unbiased, but highly correlated training sets inflate variance and it is expensive",
            "k = 2 — lowest bias",
            "k = 10 — lowest variance always",
            "k = n and k = 2 are equivalent",
        ],
        "answer": [0],
        "explanation": "LOO uses n−1 samples for training each time (low bias), but the training sets differ by one point and estimates are highly correlated, increasing variance; the variance-bias tradeoff is why 5- or 10-fold is common.",
    },
    {
        "subject": "ML", "topic": "Evaluation", "difficulty": "hard", "experience_min": 4,
        "type": "numerical",
        "text": "A model's precision at threshold t is 0.8 and recall is 0.5. Raising the threshold typically:",
        "options": [
            "Raises precision and lowers recall — fewer positives are predicted, so those predicted tend to be true positives, but more real positives are missed",
            "Raises both precision and recall",
            "Lowers precision and raises recall",
            "Has no effect",
        ],
        "answer": [0],
        "explanation": "A higher decision threshold means fewer positive predictions: precision usually increases (each predicted positive is more confident), while recall decreases (more true positives fall below the threshold). The precision–recall curve shows this tradeoff.",
    },
    {
        "subject": "ML", "topic": "Deep Learning", "difficulty": "very_hard", "experience_min": 8,
        "type": "single",
        "text": "A deep network trains very slowly and early layers learn almost nothing. Which statement is correct?",
        "options": [
            "This is the vanishing gradient problem: backpropagated gradients shrink through many multiplicative weight products; ReLU, residual connections, and careful initialization (e.g. He) mitigate it",
            "It is caused by too much dropout",
            "Batch normalization always causes it",
            "The solution is always to use a smaller model",
        ],
        "answer": [0],
        "explanation": "Sigmoid/tanh saturate and multiply small derivatives across depth, starving early layers; ReLU + He initialization + residuals (and batch norm) keep gradient magnitudes stable. The symptom of slow early-layer learning with fast later layers is classic vanishing gradients.",
    },
    {
        "subject": "ML", "topic": "Clustering", "difficulty": "expert", "experience_min": 8,
        "type": "single",
        "text": "Which statement about the silhouette score is correct?",
        "options": [
            "It combines intra-cluster cohesion and inter-cluster separation per sample, ranging from −1 (bad) to +1 (good); the mean over samples evaluates overall cluster quality without ground truth",
            "It requires labeled ground truth",
            "It is always higher for more clusters",
            "It cannot be used with k-means",
        ],
        "answer": [0],
        "explanation": "s(i) = (b(i) − a(i)) / max(a(i), b(i)) where a is mean intra-cluster distance and b is mean distance to the nearest other cluster; no labels needed. It does not monotonically favor more clusters.",
    },

    # ---------------- AI (+8) ----------------
    {
        "subject": "AI", "topic": "Search", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "Which condition on the heuristic guarantees that A* returns an optimal path with a tree search?",
        "options": [
            "Admissibility: h(n) never overestimates the true cost to the goal",
            "h(n) never underestimates",
            "h(n) = 0 for all nodes",
            "The heuristic must be a constant",
        ],
        "answer": [0],
        "explanation": "An admissible heuristic (h ≤ h*) ensures the first goal popped by A* is optimal in tree search; consistency (h ≤ c + h') additionally guarantees optimality and efficiency for graph search.",
    },
    {
        "subject": "AI", "topic": "Adversarial Search", "difficulty": "very_hard", "experience_min": 7,
        "type": "numerical",
        "text": "In a game tree where each node has 3 children and depth is 4, with optimal move ordering and alpha-beta pruning, approximately how many leaf evaluations are needed (full tree = 81)?",
        "options": [
            "17 leaves — with perfect ordering alpha-beta evaluates b^ceil(d/2) + b^floor(d/2) − 1 = 9 + 9 − 1 leaves",
            "81 leaves — pruning never skips leaves",
            "About 27 leaves",
            "9 leaves",
        ],
        "answer": [0],
        "explanation": "With optimal move ordering, alpha-beta evaluates b^(ceil(d/2)) + b^(floor(d/2)) − 1 leaves: 3^2 + 3^2 − 1 = 17, versus 81 for plain minimax — the effective branching factor becomes √b ≈ 1.73, which is why deep game searches are feasible.",
    },
    {
        "subject": "AI", "topic": "Knowledge Representation", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "What distinguishes first-order logic (FOL) from propositional logic?",
        "options": [
            "FOL adds quantified variables over objects (∀, ∃), constants, and predicates/functions, enabling statements like 'all humans are mortal' that propositional logic cannot express without enumerating every individual",
            "FOL has no truth values",
            "FOL cannot represent conjunctions",
            "FOL is probabilistic",
        ],
        "answer": [0],
        "explanation": "Propositional logic deals with fixed atomic sentences; FOL adds terms, predicates, and quantifiers so generalizations can be stated compactly — the key expressive leap for knowledge-based systems.",
    },
    {
        "subject": "AI", "topic": "Reasoning", "difficulty": "hard", "experience_min": 4,
        "type": "scenario",
        "text": "A rule-based expert system uses backward chaining to answer whether 'patient needs surgery' given rules and facts. Which statement describes backward chaining?",
        "options": [
            "It starts from the goal and works backwards through rules whose conclusions match the goal, recursing into their premises — goal-directed reasoning",
            "It starts from all facts and derives everything possible",
            "It randomly picks rules",
            "It requires a neural network",
        ],
        "answer": [0],
        "explanation": "Backward chaining is goal-directed: prove the goal by finding rules that conclude it, then prove their premises recursively (Prolog-style). Forward chaining starts from facts and derives all conclusions (data-driven).",
    },
    {
        "subject": "AI", "topic": "Constraint Satisfaction", "difficulty": "very_hard", "experience_min": 6,
        "type": "single",
        "text": "In constraint satisfaction, what does arc consistency (AC-3) guarantee after it terminates?",
        "options": [
            "Every value remaining in each variable's domain is consistent with at least one value of every neighboring variable — pruning domains without finding a solution",
            "A complete solution",
            "That the problem is unsatisfiable",
            "That backtracking is never needed",
        ],
        "answer": [0],
        "explanation": "AC-3 enforces binary arc consistency, removing values with no supporting value in a neighbor's domain. It prunes but does not solve; search (backtracking) is still required, though the search space is smaller.",
    },
    {
        "subject": "AI", "topic": "Expert Systems", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "In a production-rule system, when multiple rules match the working memory, how is the conflict resolved (typical strategy)?",
        "options": [
            "By a conflict-resolution strategy such as specificity (most conditions), recency (most recently matched), or rule priority — the chosen rule fires and the cycle repeats",
            "All matching rules fire simultaneously",
            "The first rule ever defined always fires",
            "Rules never conflict",
        ],
        "answer": [0],
        "explanation": "The recognize–act cycle selects one rule from the conflict set using strategies like specificity/recency/refractoriness. Firing all matches simultaneously would break the intended control flow.",
    },
    {
        "subject": "AI", "topic": "Probabilistic Reasoning", "difficulty": "expert", "experience_min": 9,
        "type": "single",
        "text": "In a Bayesian network, which statement about d-separation is correct?",
        "options": [
            "Two variables are conditionally independent given an evidence set if every path between them is blocked by that set; a collider (converging arrows) BLOCKS dependence unless the collider or one of its descendants is observed",
            "Colliders always block independence",
            "Observing a collider makes its parents independent",
            "d-separation only applies to continuous variables",
        ],
        "answer": [0],
        "explanation": "d-separation defines graphical independence: chains and forks are blocked by observing the middle; a collider is unblocked by observing it or a descendant (explaining-away). This underpins efficient inference.",
    },
    {
        "subject": "AI", "topic": "Planning", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "In STRIPS planning, what is a 'plan'?",
        "options": [
            "A sequence of actions whose preconditions hold in sequence, transforming the initial state into a state satisfying the goal",
            "A set of logical axioms",
            "A decision tree over actions",
            "A Markov decision process policy",
        ],
        "answer": [0],
        "explanation": "STRIPS actions have preconditions and add/delete effects; a plan is an ordered action sequence that can be applied from the initial state to reach a goal state. Planning searches this space (forward, backward, or partial-order).",
    },

    # ---------------- PY (+6) ----------------
    {
        "subject": "PY", "topic": "Data Structures", "difficulty": "hard", "experience_min": 3,
        "type": "code",
        "text": "import copy\na = [[1, 2], [3, 4]]\nb = copy.copy(a)\nb[0][0] = 99\nb.append([5])\nWhat is the state of a?",
        "options": [
            "a == [[99, 2], [3, 4]] — shallow copy shares the inner lists; appending to b does not affect a",
            "a == [[1, 2], [3, 4]]",
            "a == [[99, 2], [3, 4], [5]]",
            "a is b",
        ],
        "answer": [0],
        "explanation": "copy.copy creates a new outer list whose elements reference the SAME inner lists, so mutating b[0] changes a's inner list; b.append only changes b's length. copy.deepcopy would duplicate the inner lists.",
    },
    {
        "subject": "PY", "topic": "Language Internals", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "What is the purpose of *args and **kwargs in a function definition?",
        "options": [
            "*args collects extra positional arguments into a tuple, **kwargs collects extra keyword arguments into a dict — used for flexible/variadic interfaces and delegation",
            "*args collects keywords and **kwargs collects positionals",
            "They multiply numbers",
            "They are only valid in classes",
        ],
        "answer": [0],
        "explanation": "The single star gathers positional extras into a tuple; the double star gathers keyword extras into a dict. In call positions they do the inverse (unpacking).",
    },
    {
        "subject": "PY", "topic": "Decorators", "difficulty": "very_hard", "experience_min": 6,
        "type": "code",
        "text": "@dec_a\n@dec_b\ndef f(): ...\nWhich application order is correct?",
        "options": [
            "f = dec_a(dec_b(f)) — dec_b is applied first (innermost), then dec_a wraps it",
            "f = dec_b(dec_a(f))",
            "They are applied in alphabetical order",
            "Decorators do not nest",
        ],
        "answer": [0],
        "explanation": "Decorator syntax applies bottom-up: the nearest decorator (dec_b) wraps f first, then dec_a wraps the result. This matters when decorators add/remove attributes or stack behavior.",
    },
    {
        "subject": "PY", "topic": "Concurrency", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "Why do I/O-bound programs benefit from threads in CPython despite the GIL?",
        "options": [
            "The GIL is released during blocking I/O (socket/disk waits), so other threads run while one waits — concurrency from overlapping waits",
            "The GIL only affects CPU-bound code and is always released",
            "Threads bypass the GIL entirely",
            "The interpreter uses one thread at a time with no switching",
        ],
        "answer": [0],
        "explanation": "Blocking syscalls release the GIL, so I/O-bound workloads overlap waits across threads — throughput improves. Pure CPU work holds the GIL, which is why multiprocessing is needed there.",
    },
    {
        "subject": "PY", "topic": "Performance", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "What does bytes vs str represent in Python 3?",
        "options": [
            "str is a sequence of Unicode code points; bytes is a sequence of raw bytes. Encoding/decoding (e.g. utf-8) converts between them, and mixing them raises TypeError",
            "They are interchangeable",
            "bytes stores Unicode directly",
            "str is always ASCII-only",
        ],
        "answer": [0],
        "explanation": "Python 3 draws a hard line: text (str, Unicode) vs binary (bytes). Concatenating or comparing them raises TypeError; conversion requires explicit encode/decode. This is the source of most 'expected str, got bytes' bugs.",
    },
    {
        "subject": "PY", "topic": "Exceptions", "difficulty": "hard", "experience_min": 3,
        "type": "code",
        "text": "try:\n    raise ValueError('first')\nexcept ValueError as e:\n    raise RuntimeError('second') from e\nWhat does the traceback show, and what is __cause__?",
        "options": [
            "The RuntimeError with 'second' is raised, explicitly chained to the ValueError via 'from e', so e.__cause__ is the ValueError and the traceback prints 'The above exception was the direct cause'",
            "Only the ValueError propagates",
            "The RuntimeError has no connection to the ValueError",
            "A SyntaxError is raised",
        ],
        "answer": [0],
        "explanation": "'raise ... from e' sets __cause__ and prints the explicit-causation chain. Without 'from', the original exception becomes __context__ (implicit chaining). This makes failure diagnosis much easier.",
    },

    # ---------------- WEB (+8) ----------------
    {
        "subject": "WEB", "topic": "Security", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "When does the browser send a CORS preflight (OPTIONS) request?",
        "options": [
            "Before a cross-origin request that is not a 'simple request' — e.g. custom headers, non-simple methods, or certain content types — to ask the server which origins/methods are allowed",
            "Before every request, including same-origin",
            "Only for GET requests",
            "Never in modern browsers",
        ],
        "answer": [0],
        "explanation": "Simple requests (GET/POST/HEAD with safelisted headers and a few content types) skip preflight; anything else triggers OPTIONS preflight. The server's Access-Control-Allow-* headers decide whether the actual request proceeds.",
    },
    {
        "subject": "WEB", "topic": "Security", "difficulty": "hard", "experience_min": 4,
        "type": "single",
        "text": "Which cookie attribute prevents JavaScript from reading the cookie and thereby mitigates XSS-based cookie theft?",
        "options": ["HttpOnly", "Secure", "SameSite=Lax", "Expires"],
        "answer": [0],
        "explanation": "HttpOnly excludes the cookie from document.cookie, so injected scripts cannot read it. Secure restricts to HTTPS transport; SameSite mitigates CSRF, not XSS reads.",
    },
    {
        "subject": "WEB", "topic": "Browser Architecture", "difficulty": "very_hard", "experience_min": 6,
        "type": "single",
        "text": "Which statement about service workers is correct?",
        "options": [
            "Service workers are scripts that run in a separate worker context, can intercept fetch requests, and power offline caching; they require HTTPS and are controlled per-scope",
            "Service workers run on the main thread",
            "Service workers can read the DOM directly",
            "Service workers are only available on localhost",
        ],
        "answer": [0],
        "explanation": "A service worker is a fetch-intercepting script in its own worker context (no DOM access), registered per scope, requiring a secure context (localhost exempted). It enables offline-first apps and push notifications.",
    },
    {
        "subject": "WEB", "topic": "Security", "difficulty": "very_hard", "experience_min": 6,
        "type": "single",
        "text": "What is the key difference between XSS and CSRF?",
        "options": [
            "XSS executes attacker-controlled scripts in the victim's browser by injecting into the page; CSRF tricks the victim's browser into making authenticated requests the victim never intended — the payload is a request, not a script",
            "They are the same attack",
            "CSRF injects scripts into the DOM",
            "XSS requires the attacker to know the victim's password",
        ],
        "answer": [0],
        "explanation": "XSS breaks the page's code boundary (script injection); CSRF abuses the browser's automatic cookie/credential behavior to forge state-changing requests. Defenses differ: output encoding/CSP for XSS; CSRF tokens/SameSite for CSRF.",
    },
    {
        "subject": "WEB", "topic": "State Management", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "What is the difference between localStorage and sessionStorage?",
        "options": [
            "localStorage persists across sessions/tabs until explicitly cleared; sessionStorage is scoped to the tab session and is cleared when the tab closes",
            "sessionStorage persists forever",
            "localStorage is cleared on every navigation",
            "They are identical",
        ],
        "answer": [0],
        "explanation": "Both are origin-scoped key-value stores of ~5 MB, but sessionStorage's lifetime is the browsing session of the tab that created it, while localStorage survives restarts until cleared.",
    },
    {
        "subject": "WEB", "topic": "HTTP Semantics", "difficulty": "hard", "experience_min": 3,
        "type": "single",
        "text": "Which HTTP status code is most appropriate for 'the resource exists but the client lacks permission, and authentication would not help'?",
        "options": [
            "403 Forbidden",
            "401 Unauthorized",
            "404 Not Found",
            "400 Bad Request",
        ],
        "answer": [0],
        "explanation": "401 means authentication is required/insufficient (with WWW-Authenticate); 403 means the server understood the request but refuses it — credentials won't change the outcome. 404 is used for missing resources (and sometimes to hide existence).",
    },
    {
        "subject": "WEB", "topic": "Real-time", "difficulty": "very_hard", "experience_min": 7,
        "type": "single",
        "text": "When would you choose Server-Sent Events (SSE) over WebSockets?",
        "options": [
            "For one-way, server-to-client push (notifications, live feeds) over plain HTTP with automatic reconnection and no new protocol — simpler than WebSockets; WebSockets win for bidirectional, low-latency communication",
            "SSE supports bidirectional messaging",
            "SSE is always faster than WebSockets",
            "WebSockets cannot push data",
        ],
        "answer": [0],
        "explanation": "SSE is a unidirectional HTTP stream with built-in reconnection and event IDs, ideal for server push; WebSockets provide full-duplex messaging with a persistent connection, better for chat/games/live collaboration.",
    },
    {
        "subject": "WEB", "topic": "Browser Architecture", "difficulty": "very_hard", "experience_min": 6,
        "type": "single",
        "text": "Which sequence best describes the browser's rendering pipeline after the DOM/CSSOM are built?",
        "options": [
            "Style computation → layout (reflow) → paint → compositing; style or layout changes can invalidate parts of this pipeline, and compositor-only changes (transform/opacity) skip layout and paint",
            "Paint → layout → style",
            "Compositing → parsing",
            "Layout only happens on page load",
        ],
        "answer": [0],
        "explanation": "The canonical pipeline is style → layout → paint → composite. Animating transform/opacity is cheap because it runs on the compositor thread without reflow/repaint — the basis of 60fps animation guidance.",
    },
]
